### ISSUE TITLE
hda.api:Recovering from HTTP error [502 Bad Gateway]

### ISSUE THREAD

**Issue by josemanuelgis** [Digdgeo/PyVPP#1]
Hi Diego.

I'm trying to download scenes: MyWekeo = wekeo_download("VPP_Pheno",aoi, ['2019-01-01', '2019-12-31'], ['SOSV'])
MyWekeo.run().

And it generates the following error:

Downloading images...
Getting SOSV
WARNING:hda.api:Recovering from HTTP error [502 Bad Gateway], attempt 0 of 500
WARNING:hda.api:Retrying in 120 seconds
WARNING:hda.api:Recovering from HTTP error [502 Bad Gateway], attempt 1 of 500
WARNING:hda.api:Retrying in 120 seconds

In recent days I downloaded High Resolution Vegetation Phenology and Productivity products, without problems.

Do you have any idea what could be happening?.

Thank you very much for your contribution

**Comment by Digdgeo** [comment]
Hi Jose Manuel, (and sorry I didn't answer you before, I have just wacthed the issue). 

Yes, there was an update of HDA python library from wekeo and I should update my code to work properly with the new version. Luckily, you can still work with this version, the only thing open your .hdarc config file and delete the url. 

Let me know if it works if you try, please!

**Comment by josemanuelgis** [comment]
Hi Diego

Grateful for your response. At the time, I updated the link associated with the broker, and it solved at that time.

Thank you very much for the contribution
